[package]
name = "myfibonacci"
version = "0.1.0"
edition = "2025"

[dependencies]
[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
[lib]
name = "myfibonacci"
crate-type = ["cdylib"]
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]